server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
spring:
  application:
    name: D2
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:4306/d2
    username: root
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
      # show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: true
logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  domain: localhost:8080
application:
  format:
    datetime: yyyy-MM-dd HH:mm
    time: HH:mm:ss
    date: yyyy-MM-dd
  security:
    jwt:
      secret-key: d69d527360b798b822c7b463e00196b2c3e065a37eb517d494417fa0546bf12f
      expiration: 604800000 # 7 day
      refresh-token:
        expiration: 1209600000 # 14 days